apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: "2024-11-04T14:58:19Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: alertmanager
  name: storage-prometheus-alertmanager-0
  namespace: prometheus
  resourceVersion: "935654"
  uid: 61beba70-439f-45f0-97f4-3c9d1d9dd558
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: gp2
  volumeMode: Filesystem
status:
  phase: Pending
